/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package editor;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayDeque;
import java.util.Deque;

/**
 *
 * @author pradeep s
 */
public class TextEditor2 extends javax.swing.JFrame {

    /**
     * Creates new form TextEditor
     */
    public TextEditor2() {
        initComponents();
        setTitle("Text Editor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        fileChooser = new JFileChooser();
        buttonPanel = new javax.swing.JPanel();
        openButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        startSearch = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        regexCheck = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenu = new javax.swing.JMenuItem();
        saveMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenu = new javax.swing.JMenuItem();
        searchMenu = new javax.swing.JMenu();
        startSearchMenu = new javax.swing.JMenuItem();
        previousMenu = new javax.swing.JMenuItem();
        nextMenu = new javax.swing.JMenuItem();
        useRegMenu = new javax.swing.JMenuItem();

        fileChooser.setName("FileChooser"); // NOI18N
        add(fileChooser);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 450));
        setPreferredSize(new java.awt.Dimension(650, 450));

        buttonPanel.setMaximumSize(new java.awt.Dimension(650, 30));
        buttonPanel.setMinimumSize(new java.awt.Dimension(650, 30));
        buttonPanel.setName(""); // NOI18N
        buttonPanel.setPreferredSize(new java.awt.Dimension(650, 30));

        openButton.setText("Open");
        openButton.setMaximumSize(new java.awt.Dimension(40, 40));
        openButton.setMinimumSize(new java.awt.Dimension(40, 23));
        openButton.setName("OpenButton"); // NOI18N
        openButton.setPreferredSize(new java.awt.Dimension(40, 23));
        openButton.addActionListener(evt -> openButtonActionPerformed(evt));

        saveButton.setText("Save");
        saveButton.setMaximumSize(new java.awt.Dimension(40, 23));
        saveButton.setMinimumSize(new java.awt.Dimension(40, 23));
        saveButton.setName("SaveButton"); // NOI18N
        saveButton.setPreferredSize(new java.awt.Dimension(40, 23));
        saveButton.addActionListener(evt -> saveButtonActionPerformed(evt));

        searchField.setMinimumSize(new java.awt.Dimension(60, 25));
        searchField.setName("SearchField"); // NOI18N
        searchField.setPreferredSize(new java.awt.Dimension(60, 25));

        startSearch.setText("Start");
        startSearch.setMaximumSize(new java.awt.Dimension(40, 23));
        startSearch.setMinimumSize(new java.awt.Dimension(40, 23));
        startSearch.setName("StartSearchButton"); // NOI18N
        startSearch.setPreferredSize(new java.awt.Dimension(40, 23));
        startSearch.addActionListener(evt -> startSearchActionPerformed(evt));

        prevButton.setText("Prev");
        prevButton.setMaximumSize(new java.awt.Dimension(40, 23));
        prevButton.setMinimumSize(new java.awt.Dimension(40, 23));
        prevButton.setName("PreviousMatchButton"); // NOI18N
        prevButton.setPreferredSize(new java.awt.Dimension(40, 23));
        prevButton.addActionListener(evt -> prevButtonActionPerformed(evt));

        nextButton.setText("Next");
        nextButton.setMaximumSize(new java.awt.Dimension(40, 23));
        nextButton.setMinimumSize(new java.awt.Dimension(40, 23));
        nextButton.setName("NextMatchButton"); // NOI18N
        nextButton.setPreferredSize(new java.awt.Dimension(40, 23));
        nextButton.addActionListener(evt -> nextButtonActionPerformed(evt));

        regexCheck.setText("Use Regex");
        regexCheck.setMaximumSize(new java.awt.Dimension(40, 23));
        regexCheck.setMinimumSize(new java.awt.Dimension(40, 23));
        regexCheck.setName("UseRegExCheckbox"); // NOI18N
        regexCheck.setPreferredSize(new java.awt.Dimension(40, 23));
        regexCheck.addActionListener(evt -> regexCheckActionPerformed(evt));

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
                buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(buttonPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(openButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prevButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(regexCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
                buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(openButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(startSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(regexCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(prevButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {nextButton, openButton, prevButton, regexCheck, saveButton, searchField, startSearch});

        jScrollPane1.setName("ScrollPane"); // NOI18N

        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.setName("TextArea"); // NOI18N
        jScrollPane1.setViewportView(textArea);

        jMenuBar1.setMaximumSize(new java.awt.Dimension(650, 25));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(650, 25));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(650, 25));

        fileMenu.setText("File");
        fileMenu.setName("MenuFile"); // NOI18N

        openMenu.setText("Open");
        openMenu.setName("MenuOpen"); // NOI18N
        openMenu.addActionListener(evt -> openButtonActionPerformed(evt));
        fileMenu.add(openMenu);

        saveMenu.setText("Save");
        saveMenu.setName("MenuSave"); // NOI18N
        saveMenu.addActionListener(evt -> saveButtonActionPerformed(evt));
        fileMenu.add(saveMenu);
        fileMenu.add(jSeparator1);

        exitMenu.setText("Exit");
        exitMenu.setName("MenuExit"); // NOI18N
        exitMenu.addActionListener(evt -> System.exit(0));
        fileMenu.add(exitMenu);

        jMenuBar1.add(fileMenu);

        searchMenu.setText("Search");
        searchMenu.setName("MenuSearch"); // NOI18N

        startSearchMenu.setText("Start Search");
        startSearchMenu.setName("MenuStartSearch"); // NOI18N
        searchMenu.add(startSearchMenu);

        previousMenu.setText("Previous Match");
        previousMenu.setName("MenuPreviousMatch"); // NOI18N
        searchMenu.add(previousMenu);

        nextMenu.setText("Next Match");
        nextMenu.setName("MenuNextMatch"); // NOI18N
        searchMenu.add(nextMenu);

        useRegMenu.setText("Use Regular Expression");
        useRegMenu.setName("MenuUseRegExp"); // NOI18N
        searchMenu.add(useRegMenu);

        jMenuBar1.add(searchMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int returnValue = fileChooser.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            currentFile = fileChooser.getSelectedFile();
            System.out.println("Current File Chosen: " + currentFile.getAbsolutePath());
            fileOpened = true;
        }

        textArea.setText("");

        try {
            String text = Files.readString(Paths.get(currentFile.getAbsolutePath()));
            textArea.setText(text);
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (fileOpened) {
            try {
                writer = new FileWriter(currentFile);
                String toWrite = textArea.getText();
                writer.write(toWrite);
                writer.flush();
                writer.close();
            } catch (IOException e) {
                System.out.println("Oops, file not found. File may have been deleted");
            }
        } else {
            int returnValue = fileChooser.showSaveDialog(null);

            if (returnValue == JFileChooser.APPROVE_OPTION) {
                currentFile = fileChooser.getSelectedFile();
                System.out.println("Current file saved to: " + currentFile.getAbsolutePath());
                fileOpened = true;
            }
        }

    }

    private void startSearchActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        sText = searchField.getText();
        searchTermLength = sText.length();
        System.out.println(sText);
        currIndex = textArea.getText().indexOf(sText); // gets the first index of the search term
        indexStack.offerLast(currIndex); // add to stack

        textArea.setCaretPosition(currIndex + searchTermLength);
        textArea.select(currIndex, currIndex + searchTermLength);
        textArea.grabFocus();
    }

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (!backAlreadyPressed) {
            indexStack.pollLast();
        }

        int prevIndex = indexStack.pollLast();
        System.out.println("PrevIndex: " + prevIndex);
        currIndex = textArea.getText().indexOf(sText, prevIndex); // gets the prev index

        textArea.setCaretPosition(currIndex - searchTermLength);
        textArea.select(currIndex, currIndex + searchTermLength);
        textArea.grabFocus();

        backAlreadyPressed = true;
    }

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int nextIndex = currIndex + searchTermLength;
        currIndex = textArea.getText().indexOf(sText, nextIndex); // gets the next index of search term
        System.out.println("Next Index: " + currIndex);

        if (currIndex != -1) {
            indexStack.offerLast(currIndex);
            textArea.setCaretPosition(currIndex + searchTermLength);
            textArea.select(currIndex, currIndex + searchTermLength);
            textArea.grabFocus();

            backAlreadyPressed = false;
        }

    }

    private void regexCheckActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (regex){
            regex = false;
        } else {
            regex = true;
        }
    }



    private void iconResize(ImageIcon x) {
        Image newImg = x.getImage().getScaledInstance(10, 10, Image.SCALE_SMOOTH);
        x.setImage(newImg);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextEditor2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextEditor2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextEditor2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextEditor2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextEditor2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JMenuItem exitMenu;
    private JFileChooser fileChooser;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton nextButton;
    private javax.swing.JMenuItem nextMenu;
    private javax.swing.JButton openButton;
    private javax.swing.JMenuItem openMenu;
    private javax.swing.JButton prevButton;
    private javax.swing.JMenuItem previousMenu;
    private javax.swing.JCheckBox regexCheck;
    private javax.swing.JButton saveButton;
    private javax.swing.JMenuItem saveMenu;
    private javax.swing.JTextField searchField;
    private javax.swing.JMenu searchMenu;
    private javax.swing.JButton startSearch;
    private javax.swing.JMenuItem startSearchMenu;
    private javax.swing.JTextArea textArea;
    private javax.swing.JMenuItem useRegMenu;
    // End of variables declaration

    // Icons
    ImageIcon saveIcon = new ImageIcon("C:\\Users\\pradeep shanbhogue\\IdeaProjects\\Text Editor1\\Text Editor\\task\\src\\editor\\save.png");
    ImageIcon openIcon = new ImageIcon("C:\\Users\\pradeep shanbhogue\\IdeaProjects\\Text Editor1\\Text Editor\\task\\src\\editor\\open.png");
    ImageIcon prevIcon = new ImageIcon("C:\\Users\\pradeep shanbhogue\\IdeaProjects\\Text Editor1\\Text Editor\\task\\src\\editor\\prev.png");
    ImageIcon nextIcon = new ImageIcon("C:\\Users\\pradeep shanbhogue\\IdeaProjects\\Text Editor1\\Text Editor\\task\\src\\editor\\next.png");
    ImageIcon searchIcon = new ImageIcon("C:\\Users\\pradeep shanbhogue\\IdeaProjects\\Text Editor1\\Text Editor\\task\\src\\editor\\search.png");

    // File variables
    private File file = null;
    private FileWriter writer;
    private String file_name; // hold the name of the file
    private File currentFile; // keep track of the current file
    private String path = "C:\\Users\\pradeep shanbhogue\\IdeaProjects\\Text Editor1\\Text Editor\\task";
    private boolean fileOpened = false;

    // Search variables
    int currIndex = 0;
    int searchTermLength = 0;
    String sText = "";
    boolean backAlreadyPressed = false;
    boolean regex = false;
    Deque<Integer> indexStack = new ArrayDeque<>();
}
